name       : gnome-photos
version    : 3.24.2
release    : 13
source     :
    - https://download.gnome.org/sources/gnome-photos/3.24/gnome-photos-3.24.2.tar.xz : 31ddc078ad2f6bc4bbfa2f71eb23377782750b9cb2ad2b0e6ff2a1971548cdf9
license    : GPL-2.0
component  : multimedia.graphics
summary    : Access, organize, and share your photos on GNOME
description: |
    Access, organize, and share your photos on GNOME
builddeps  :
    - pkgconfig(babl)
    - pkgconfig(dleyna-server-service-1.0)
    - pkgconfig(exempi-2.0)
    - pkgconfig(gegl-0.3)
    - pkgconfig(geocode-glib-1.0)
    - pkgconfig(gexiv2)
    - pkgconfig(gio-2.0)
    - pkgconfig(gnome-desktop-3.0)
    - pkgconfig(grilo-0.3)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(lcms2)
    - pkgconfig(libexif)
    - pkgconfig(libgdata)
    - pkgconfig(libgfbgraph-0.2)
    - pkgconfig(libraw)
    - pkgconfig(librsvg-2.0)
    - pkgconfig(python-2.7)
    - pkgconfig(tracker-control-1.0)
    - pkgconfig(yelp-xsl)
    - desktop-file-utils
    - grilo-plugins
    - itstool
    - libjpeg-turbo-devel
    - yelp-devel
    - yelp-tools
rundeps    :
    - dleyna-renderer
    - grilo-plugins
setup      : |
    sed -i 's/Utility;/Graphics;/' data/org.gnome.Photos.desktop.in.in
    %patch -p1 < $pkgfiles/0001-Don-t-explicitly-force-libpng16-ask-for-libpng.patch
    %reconfigure --disable-static
build      : |
    %make
install    : |
    %make_install
