name       : gnome-photos
version    : 3.38.0
release    : 46
source     :
    - https://download.gnome.org/sources/gnome-photos/3.38/gnome-photos-3.38.0.tar.xz : 667f39477579d577470740e01f37b05c62e461e6f6da6377724d8f3993e1c4c4
license    : GPL-2.0-or-later
component  : multimedia.graphics
summary    : Access, organize, and share your photos on GNOME
description: |
    A simple application to access, organize and share your photos on GNOME. It is meant to be a simple and elegant replacement for using a file manager to deal with photos. Seamless cloud integration is offered through GNOME Online Accounts.
builddeps  :
    - pkgconfig(dleyna-server-service-1.0)
    - pkgconfig(exempi-2.0)
    - pkgconfig(gegl-0.4)
    - pkgconfig(geocode-glib-1.0)
    - pkgconfig(gexiv2)
    - pkgconfig(gnome-desktop-3.0)
    - pkgconfig(grilo-0.3)
    - pkgconfig(lcms2)
    - pkgconfig(libdazzle-1.0)
    - pkgconfig(libexif)
    - pkgconfig(libgdata)
    - pkgconfig(libgfbgraph-0.2)
    - pkgconfig(libraw)
    - pkgconfig(librsvg-2.0)
    - pkgconfig(libturbojpeg)
    - pkgconfig(tracker-sparql-3.0)
    - pkgconfig(yelp-xsl)
    - desktop-file-utils
    - grilo-plugins
    - itstool
    - yelp-devel
    - yelp-tools
rundeps    :
    - grilo-plugins
setup      : |
    %apply_patches
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
