name       : gnome-photos
version    : 3.26.4
release    : 20
source     :
    - https://download.gnome.org/sources/gnome-photos/3.26/gnome-photos-3.26.4.tar.xz : 846185cfa3573a29063960757907ef1f943d5e46a02aad4bd493608238901dbb
license    : GPL-2.0-or-later
component  : multimedia.graphics
summary    : Access, organize, and share your photos on GNOME
description: |
    A simple application to access, organize and share your photos on GNOME. It is meant to be a simple and elegant replacement for using a file manager to deal with photos. Seamless cloud integration is offered through GNOME Online Accounts.
builddeps  :
    - pkgconfig(dleyna-server-service-1.0)
    - pkgconfig(exempi-2.0)
    - pkgconfig(gegl-0.3)
    - pkgconfig(geocode-glib-1.0)
    - pkgconfig(gexiv2)
    - pkgconfig(gnome-desktop-3.0)
    - pkgconfig(grilo-0.3)
    - pkgconfig(lcms2)
    - pkgconfig(libexif)
    - pkgconfig(libgdata)
    - pkgconfig(libgfbgraph-0.2)
    - pkgconfig(libraw)
    - pkgconfig(librsvg-2.0)
    - pkgconfig(libturbojpeg)
    - pkgconfig(tracker-control-2.0)
    - pkgconfig(yelp-xsl)
    - desktop-file-utils
    - grilo-plugins
    - itstool
    - yelp-devel
    - yelp-tools-devel
rundeps    :
    - dleyna-renderer
    - grilo-plugins
setup      : |
    sed -i 's/Utility;/Graphics;/' data/org.gnome.Photos.desktop.in.in
    %patch -p1 < $pkgfiles/0001-Don-t-explicitly-force-libpng16-ask-for-libpng.patch
    %reconfigure --disable-static
build      : |
    %make
install    : |
    %make_install
