name       : gnome-photos
version    : 3.18.3
release    : 1
source     :
    - http://ftp.gnome.org/pub/GNOME/sources/gnome-photos/3.18/gnome-photos-3.18.3.tar.xz : cb0b0573b2b473257a41024de7b99986a10a67af07cbdead5bf266291e9ed167
license    : GPL-2.0
component  : desktop.multimedia
summary    : Access, organize, and share your photos on GNOME
description: |
    Access, organize, and share your photos on GNOME
builddeps  :
    - pkgconfig(babl)
    - pkgconfig(dleyna-server-service-1.0)
    - pkgconfig(exempi-2.0)
    - pkgconfig(gegl-0.3)
    - pkgconfig(gexiv2)
    - pkgconfig(gio-2.0)
    - pkgconfig(gnome-desktop-3.0)
    - pkgconfig(grilo-0.2)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(lcms2)
    - pkgconfig(libexif)
    - pkgconfig(libgdata)
    - pkgconfig(libgfbgraph-0.2)
    - pkgconfig(libraw)
    - pkgconfig(librsvg-2.0)
    - pkgconfig(python-2.7)
    - pkgconfig(tracker-control-1.0)
    - desktop-file-utils
    - grilo-plugins
    - itstool
rundeps    :
    - grilo-plugins
setup      : |
    sed -i 's/Utility;/Graphics;/' data/org.gnome.Photos.desktop.in.in
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
