name       : gnome-photos
version    : '42.0'
release    : 47
source     :
    - https://download.gnome.org/sources/gnome-photos/42/gnome-photos-42.0.tar.xz : 25cb281425199dec7b045f13f32f8f96034cb0cb8b94d96f9dffaf4f5be68551
homepage   : https://wiki.gnome.org/Apps/Photos
license    : GPL-2.0-or-later
component  : multimedia.graphics
summary    : Access, organize, and share your photos on GNOME
description: |
    A simple application to access, organize and share your photos on GNOME. It is meant to be a simple and elegant replacement for using a file manager to deal with photos. Seamless cloud integration is offered through GNOME Online Accounts.
builddeps  :
    - pkgconfig(dleyna-server-service-1.0)
    - pkgconfig(gegl-0.4)
    - pkgconfig(geocode-glib-1.0)
    - pkgconfig(gexiv2)
    - pkgconfig(gnome-desktop-3.0)
    - pkgconfig(grilo-0.3)
    - pkgconfig(lcms2)
    - pkgconfig(libdazzle-1.0)
    - pkgconfig(libexif)
    - pkgconfig(libgdata)
    - pkgconfig(libgfbgraph-0.2)
    - pkgconfig(libhandy-1)
    - pkgconfig(libraw)
    - pkgconfig(librsvg-2.0)
    - pkgconfig(libturbojpeg)
    - pkgconfig(tracker-sparql-3.0)
    - pkgconfig(yelp-xsl)
    - desktop-file-utils
    - grilo-plugins
    - itstool
    - yelp-devel
    - yelp-tools
rundeps    :
    - grilo-plugins
setup      : |
    %apply_patches
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
